[project]
name = "mmore"
version = "0.1.0"
description = "mmore: Scalable multimodal document extraction pipeline for custom RAG integration."
authors = [
]
requires-python = ">=3.10"
dependencies = [
    "surya-ocr",
    "requests",
    "Pillow",
    "PyMuPDF",
    "python-docx",
    "python-pptx",
    "selenium",
    "clean-text",
    "Unidecode",
    "docx2pdf",
    "validators",
    "rarfile",
    "openpyxl",
    "xlrd",
    "py7zr",
    "pandas",
    "validators",
    "rarfile",
    "markdown",
    "markdownify",
    "trafilatura",
    "moviepy",
    "chonkie",
    "langdetect",
    "datatrove[processing]",
    "transformers==4.46.2",
    "datasets",
    "langchain",
    "langchain-milvus",
    "langchain-huggingface",
    "langchain-openai",
    "langchain-anthropic",
    "langchain-mistralai",
    "langchain-cohere",
    "langchain-aws",
    "langchain-nvidia-ai-endpoints",
    "langchain-google-vertexai",
    "langserve",
    "pymilvus[model]",
    "xformers",
    "ragas",
    "nltk",
    "python-dotenv",
    "dacite",
    "validators",
    "fastapi",
    "uvicorn",
    "httpx==0.27.2",
    "click>=8.1.7",
    "ucx-py-cu12>=0.40.0",
    "marker-pdf==0.3.10",
]

[project.optional-dependencies]
cpu = [
    "torch>=2.5.1",
]
cu124 = [
    "torch>=2.5.1",
]


[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu124" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
  { index = "pytorch-cu124", extra="cu124", marker = "platform_machine != 'aarch64'"},
  # { url = "https://download.pytorch.org/whl/cu124/torch-2.5.1-cp311-cp311-linux_aarch64.whl", extra="cu124",  marker = "platform_machine == 'aarch64'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[project.scripts]
mmore = "mmore:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"