pp_modules:
  - type: filter_language
    args:
      exclusion_writer: examples/example_outputs_ner/logs/language.jsonl
      languages: ["en"]
  - type: filter_fineweb
    args:
      exclusion_writer: examples/example_outputs_ner/logs/fineweb.jsonl
  - type: chunker 
    args:
      chunking_strategy: sentence
  - type: lang_detector
output:
  output_path: examples/example_outputs_ner/pp
  save_each_step: True