indexer:
  dense_model:
    model_name: meta-llama/Llama-3.2-11B-Vision
    is_multimodal: true
  sparse_model:
    model_name: splade
  db:
    uri: ./examples/index/llamavision/ner.db
collection_name: my_docs
documents_path: examples/example_outputs_ner