indexer:
  dense_model_name: sentence-transformers/all-MiniLM-L6-v2
  sparse_model_name: splade
  db:
    uri: ./examples/index/med_demo.db
    name: db
  pp:
    - type: chunker 
      args:
        chunking_strategy: sentence
    - type: ner
      args:
        llm:
          llm_name: "gpt-4o-mini"
    - type: lang_detector
collection_name: my_docs
documents_path: examples/example_outputs_ner